---
- name: Delete object on {{ endpoint.path }}
  ansible.builtin.uri:
    url: "{{ api_base_url }}{{ endpoint.path }}{{ obj_id }}/"
    headers: "{{ api_headers }}"
    method: DELETE
    validate_certs: "{{ nautobot_validate_certs }}"
    status_code: 204
  when: obj_id is defined
  ignore_errors: "{{ continue_on_error | bool }}"