# roles/nautobot_discovery/tasks/assign_ip_to_interface.yml
---
- name: Assign IPs to interface {{ intf.name }}
  set_fact:
    ip_to_interface_bodies: >-
      {{ ip_to_interface_bodies + [
           {
             'ip_address': {'id': ip_id_map[ip]},
             'interface': {'id': interface_ids[intf.name]}
           }
         ] }}
  loop: "{{ intf.ip_addresses | default([]) }}"
  loop_control:
    loop_var: ip
  when:
    - ip in ip_id_map
    - intf.name in interface_ids
    - ip_id_map[ip] is defined
    - interface_ids[intf.name] is defined