---
- name: Parse IP address
  ansible.builtin.command: python -c "import ipaddress; interface = ipaddress.ip_interface('{{ ip }}'); print(str(interface.ip)); print(str(interface.network.prefixlen)); print(str(interface.network))"
  register: ip_compute
  changed_when: false

- name: Set IP facts
  set_fact:
    ip_host: "{{ ip_compute.stdout_lines[0] }}"
    ip_mask: "{{ ip_compute.stdout_lines[1] }}"
    ip_prefix: "{{ ip_compute.stdout_lines[2] }}"