---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.prefixes }}"
    filters:
      prefix: "{{ ip_prefix }}"
      namespace: "{{ nautobot_namespace }}"
      vrf: "{{ vrf_ids[prefix_vrf] if prefix_vrf is defined and prefix_vrf in vrf_ids else omit }}"
    var_name: prefix_list

- name: Set existing prefix
  set_fact:
    prefix: "{{ prefix_list[0] if prefix_list | length > 0 else {} }}"

- name: Create or update prefix
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.prefixes }}"
    obj_id: "{{ prefix.id if prefix.id is defined }}"
    body:
      prefix: "{{ ip_prefix }}"
      namespace: "{{ nautobot_namespace }}"
      status: "{{ nautobot_status }}"
      vrf:
        id: "{{ vrf_ids[prefix_vrf] if prefix_vrf is defined and prefix_vrf in vrf_ids else omit }}"
    var_name: prefix
  when: prefix_list | length == 0 or prefix.id is defined

- set_fact:
    prefix_ids: "{{ prefix_ids | default({}) | combine({(prefix_vrf|default('')) ~ ':' ~ ip_prefix: prefix.id}) if prefix_vrf is defined else prefix_ids | combine({ip_prefix: prefix.id}) }}"