---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.location_types }}"
    filters:
      name: "{{ default_location_type }}"
    var_name: location_type_list

- name: Set existing location type
  set_fact:
    location_type: "{{ location_type_list[0] if location_type_list | length > 0 else {} }}"

- name: Create or update location type
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.location_types }}"
    obj_id: "{{ location_type.id | default(omit) }}"
    body:
      name: "{{ default_location_type }}"
      content_types:
        - dcim.device
        - dcim.rack
        - ipam.vlan
    var_name: location_type
  when: (location_type_list | length == 0 and create_missing_locations | bool) or location_type.id is defined

- set_fact:
    location_type_id: "{{ location_type.id }}"

- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.locations }}"
    filters:
      name: "{{ device.location }}"
      location_type: "{{ location_type_id }}"
    var_name: location_list

- name: Set existing location
  set_fact:
    location: "{{ location_list[0] if location_list | length > 0 else {} }}"

- name: Create or update location
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.locations }}"
    obj_id: "{{ location.id | default(omit) }}"
    body:
      name: "{{ device.location }}"
      location_type:
        id: "{{ location_type_id }}"
      status: "{{ nautobot_status }}"
    var_name: location
  when: (location_list | length == 0 and create_missing_locations | bool) or location.id is defined

- name: Fail if location not found and creation not allowed
  fail:
    msg: "Location {{ device.location }} not found and create_missing_locations is false"
  when: location_list | length == 0 and not create_missing_locations | bool

- set_fact:
    location_id: "{{ location.id }}"