---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.vlans }}"
    filters:
      name: "{{ vlan }}"
      location: "{{ location_id }}"
    var_name: vlan_list

- name: Set existing VLAN
  set_fact:
    vlan_obj: "{{ vlan_list[0] if vlan_list | length > 0 else {} }}"

- name: Create or update VLAN
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.vlans }}"
    obj_id: "{{ vlan_obj.id if vlan_obj.id is defined }}"
    body:
      name: "{{ vlan }}"
      vid: "{{ vlan_item.tag | default(1) }}"  # Default to 1 if tag is undefined
      location:
        id: "{{ location_id }}"
      status: "{{ nautobot_status }}"
    var_name: vlan_obj
  when: vlan_list | length == 0 or vlan_obj.id is defined

- set_fact:
    vlan_ids: "{{ vlan_ids | default({}) | combine({vlan: vlan_obj.id}) }}"