---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.tenants }}"
    filters:
      name: "{{ tenant_name | default(device.tenant) }}"
    var_name: tenant_list

- name: Set existing tenant
  set_fact:
    tenant: "{{ tenant_list[0] if tenant_list | length > 0 else {} }}"

- name: Create or update tenant
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.tenants }}"
    obj_id: "{{ tenant.id | default(omit) }}"
    body:
      name: "{{ tenant_name | default(device.tenant) }}"
    var_name: tenant
  when: (tenant_list | length == 0 and create_missing_tenants | bool) or tenant.id is defined

- name: Fail if tenant not found and creation not allowed
  fail:
    msg: "Tenant {{ tenant_name | default(device.tenant) }} not found and create_missing_tenants is false"
  when: tenant_list | length == 0 and not create_missing_tenants | bool

- set_fact:
    tenant_id: "{{ tenant.id }}"
    tenant_ids: "{{ tenant_ids | default({}) | combine({(tenant_name | default(device.tenant)): tenant.id}) }}"