---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.namespaces }}"
    filters:
      name: "{{ nautobot_namespace }}"
    var_name: namespace_list

- name: Set namespace
  set_fact:
    namespace: "{{ namespace_list[0] if namespace_list | length > 0 else {} }}"

- name: Create namespace if not found
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.namespaces }}"
    obj_id: omit
    body:
      name: "{{ nautobot_namespace }}"
      description: ""
    var_name: namespace
  when: namespace_list | length == 0

- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.vrfs }}"
    filters:
      rd: "{{ vrf_name }}"
      namespace: "{{ namespace.id }}"
    var_name: vrf_list

- name: Set existing VRF
  set_fact:
    vrf: "{{ vrf_list[0] if vrf_list | length > 0 else {} }}"

- name: Create or update VRF
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.vrfs }}"
    obj_id: "{{ vrf.id | default(omit) }}"
    body:
      name: "{{ vrf_name }}"
      rd: "{{ vrf_name }}"
      namespace:
        id: "{{ namespace.id }}"
    var_name: vrf
  when: vrf_list | length == 0 or vrf.id is defined

- name: Check existing VRF-device assignments
  ansible.builtin.uri:
    url: "{{ api_base_url }}/ipam/vrf-device-assignments/?vrf={{ vrf.id }}&device={{ device_id }}"
    headers: "{{ api_headers }}"
    method: GET
    body_format: json
    validate_certs: "{{ nautobot_validate_certs | default(false) }}"
    status_code: 200
    return_content: yes
  register: vrf_assignment_check
  when: vrf.id is defined and device_id is defined

- name: Assign VRF to device
  ansible.builtin.uri:
    url: "{{ api_base_url }}/ipam/vrf-device-assignments/"
    headers: "{{ api_headers }}"
    method: POST
    body: "{{ {'vrf': {'id': vrf.id}, 'device': {'id': device_id}} | to_json }}"
    body_format: json
    validate_certs: "{{ nautobot_validate_certs | default(false) }}"
    status_code: 201
    return_content: yes
  when: vrf.id is defined and device_id is defined and vrf_assignment_check.json.count == 0
  ignore_errors: "{{ continue_on_error | bool | default(false) }}"

- name: Update VRF IDs fact
  set_fact:
    vrf_ids: "{{ vrf_ids | default({}) | combine({vrf_name: vrf.id}) }}"
  when: vrf.id is defined