---
- name: Ensure role name is defined
  ansible.builtin.fail:
    msg: "Role name is undefined in device facts or inventory"
  when: device.role_name | default(device.device_type | default('')) == ''

- name: Perform API lookup for role
  ansible.builtin.include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.device_roles }}"
    filters:
      name: "{{ device.role_name | default(device.device_type | default('Load Balancer')) }}"
    var_name: role_list

- name: Set existing role
  ansible.builtin.set_fact:
    role: "{{ role_list[0] if role_list | length > 0 else {} }}"

- name: Define role body
  ansible.builtin.set_fact:
    role_body:
      name: "{{ device.role_name | default(device.device_type | default('Load Balancer')) }}"
      slug: "{{ (device.role_name | default(device.device_type | default('Load Balancer')) | regex_replace('[^a-zA-Z0-9]+', '-') | lower) }}"
      color: "{{ device.role_color | default('ff0000') }}"
      content_types:
        - dcim.device
      description: "{{ device.role_description | default(omit) }}"
      weight: "{{ device.role_weight | default(1000) }}"

- name: Create or update role
  ansible.builtin.include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.device_roles }}"
    obj_id: "{{ role.id | default(none) }}"
    body: "{{ role_body }}"
    var_name: role
  when: create_missing_roles | default(true)

- name: Set role ID
  ansible.builtin.set_fact:
    role_id: "{{ role.id }}"
