---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.tags }}"
    filters:
      name: "{{ tag_name }}"
    var_name: tag_list

- name: Set existing tag
  set_fact:
    tag: "{{ tag_list[0] if tag_list | length > 0 else {} }}"

- name: Create or update tag
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.tags }}"
    obj_id: "{{ tag.id if tag.id is defined }}"
    body:
      name: "{{ tag_name }}"
      content_types:
        - dcim.device
    var_name: tag
  when: tag_list | length == 0 or tag.id is defined

- set_fact:
    tag_ids: "{{ tag_ids | default([]) | append(tag.id) }}"