---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.prefixes }}"
    filters:
      prefix: "{{ ip_prefix }}"
      namespace: "{{ nautobot_namespace }}"
    var_name: prefix_list

- name: Set existing prefix
  set_fact:
    prefix: "{{ prefix_list[0] if prefix_list | length > 0 else {} }}"

- name: Create or update prefix
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.prefixes }}"
    obj_id: "{{ prefix.id | default(omit) }}"
    body:
      prefix: "{{ ip_prefix }}"
      namespace: "{{ nautobot_namespace }}"
      status: "{{ nautobot_status }}"
      tenant:
        id: "{{ tenant_ids[tenant] if tenant is defined and tenant in tenant_ids else omit }}"
    var_name: prefix
  when: prefix_list | length == 0 or prefix.id is defined

- set_fact:
    prefix_ids: "{{ prefix_ids | default({}) | combine({(prefix_vrf|default('')) ~ ':' ~ ip_prefix: prefix.id}) if prefix_vrf is defined else prefix_ids | combine({ip_prefix: prefix.id}) }}"

- name: Check existing VRF-prefix assignments
  ansible.builtin.uri:
    url: "{{ api_base_url }}/ipam/vrf-prefix-assignments/?vrf={{ vrf_ids[prefix_vrf] }}&prefix={{ prefix.id }}"
    headers: "{{ api_headers }}"
    method: GET
    validate_certs: "{{ nautobot_validate_certs | default(false) }}"
    status_code: 200
    return_content: yes
  register: vrf_assignment_check
  when: prefix_vrf is defined and prefix_vrf in vrf_ids and prefix.id is defined
  ignore_errors: "{{ continue_on_error | bool | default(false) }}"

- name: Assign prefix to VRF
  ansible.builtin.uri:
    url: "{{ api_base_url }}/ipam/vrf-prefix-assignments/"
    headers: "{{ api_headers }}"
    method: POST
    body: "{{ {'vrf': {'id': vrf_ids[prefix_vrf]}, 'prefix': {'id': prefix.id}} | to_json }}"
    body_format: json
    validate_certs: "{{ nautobot_validate_certs | default(false) }}"
    status_code: 201
    return_content: yes
  when: prefix_vrf is defined and prefix_vrf in vrf_ids and prefix.id is defined and vrf_assignment_check.json.count == 0
  ignore_errors: "{{ continue_on_error | bool | default(false) }}"