---
- include_tasks: api_lookup.yml
  vars:
    endpoint: "{{ endpoints.vrfs }}"
    filters:
      name: "{{ vrf_name }}"
    var_name: vrf_list

- name: Set existing VRF
  set_fact:
    vrf: "{{ vrf_list[0] if vrf_list | length > 0 else {} }}"

- name: Create or update VRF
  include_tasks: api_create_or_update.yml
  vars:
    endpoint: "{{ endpoints.vrfs }}"
    obj_id: "{{ vrf.id if vrf.id is defined }}"
    body:
      name: "{{ vrf_name }}"
      rd: "{{ vrf_name }}"
    var_name: vrf
  when: vrf_list | length == 0 or vrf.id is defined

- name: Assign VRF to device
  ansible.builtin.uri:
    url: "{{ api_base_url }}/ipam/vrf-device-assignments/"
    headers: "{{ api_headers }}"
    method: POST
    body: "{{ {'vrf': {'id': vrf.id}, 'device': {'id': device_id}} | to_json }}"
    body_format: json
    validate_certs: "{{ nautobot_validate_certs }}"
    status_code: 201, 200
  when: vrf.id is defined
  ignore_errors: "{{ continue_on_error | bool }}"

- set_fact:
    vrf_ids: "{{ vrf_ids | default({}) | combine({vrf_name: vrf.id}) }}"