---
create_missing_locations: true
default_location_type: "Datacenter"
create_missing_racks: true
create_missing_tenants: true
create_missing_software_versions: true
continue_on_error: false
allow_ip_overwrite: true
use_next_available_on_conflict: false
nautobot_namespace: "Global"
nautobot_status: "Active"
nautobot_validate_certs: false
prefix_ids: {}
vrf_ids: {}
tenant_ids: {}
vlan_ids: {}
rack_u_height: 42  # Standard 42U rack height
rack_type: "2-post-frame"  # Common rack type
rack_width: 19  # Standard 19-inch rack width