# roles/nautobot_discovery/defaults/main.yml
---
create_missing_locations: true
default_location_type: "Datacenter"
create_missing_racks: true
create_missing_tenants: true
create_missing_software_versions: true
continue_on_error: false
allow_ip_overwrite: true
use_next_available_on_conflict: false
nautobot_namespace: "Global"
nautobot_status: "Active"
nautobot_validate_certs: false
prefix_ids: {}
vrf_ids: {}
tenant_ids: {}
vlan_ids: {}
rack_u_height: 42
rack_type: "4-post-frame"
rack_width: 19
bulk_chunk_size: 40
nautobot_discovery_batch_size: 40
nautobot_discovery_bulk_chunk_size: 40
nautobot_discovery_retry_attempts: 3
nautobot_discovery_continue_on_error: false
nautobot_discovery_debug: false